In [1]:
cd C:\Users\micha\Dropbox\Catalyst Neuro\repos\nwb-jupyter-widgets

In [2]:
from pynwb import NWBHDF5IO
from nwbwidgets.brains import HumanElectrodesPlotlyWidget
from nwbwidgets.utils.timeseries import get_timeseries_tt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime
from ndx_events import LabeledEvents, AnnotatedEventsTable, Events

io = NWBHDF5IO(r'C:\Users\micha\Desktop\Brunton Lab Data\H5\subj_01_day_3.nwb', mode='r')
nwb = io.read()

In [3]:
HumanElectrodesPlotlyWidget(nwb.electrodes)

HumanElectrodesPlotlyWidget(children=(FigureWidget({
    'data': [{'color': 'lightgray',
              'hoveri…

In [4]:
for i, n in enumerate([0]):
    print(i, n)

0 0


In [5]:
a = np.array([x for x in range(3)])

In [6]:
a

array([0, 1, 2])

In [7]:
b = np.array([1, 1, 1])

In [8]:
a[b == 1]

array([0, 1, 2])

In [9]:
list(nwb.electrodes.colnames)

['x',
 'y',
 'z',
 'imp',
 'location',
 'filtering',
 'group',
 'group_name',
 'standard_deviation',
 'kurtosis',
 'median_deviation',
 'good',
 'low_freq_R2',
 'high_freq_R2']

In [10]:
nwb.electrodes['good'][:]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [11]:
type(nwb.electrodes['good'][0])

numpy.bool_

In [12]:
isinstance(nwb.electrodes['x'][0], np.float)

True

In [13]:
type(nwb.electrodes['z'][0])

numpy.float64